config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'auth/index'
  root'welcome#index'
  #get 'users/new'
 # get 'users/create'

 resources :users, only:[:new,:create]
 resources :sessions, only:[:new,:create,:destroy]
 delete '/logout', to: 'sessions#destroy', as: :log_out
 #get '/signup' => 'users#new', as: 'new_user_path'
 #post '/signup' => 'users#create', as: 'users_path'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    if login(params[:email],params[:password])
      redirect_to auth_index_path

    else
      render 'new'
  end

end



  def destroy

    logout #logout

    redirect_to root_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      login(params[:user][:email],params[:user][:password])
      redirect_to auth_index_path

    else

      render 'new'

    end

  end

  private
    def user_params

      params.require(:user).permit(:email,:password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideabook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
    
    
  
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', required: true %>
    </div>
    
    <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
  <% end %>

app/views/welcome/index.html.erb
<h1> Auth </h1>

<%= link_to 'Sign Up', new_user_path %>
<%= link_to 'Login ', new_session_path %>